"""Joint sampling must work with *every* surrogate backend, not just the one in use.

`sample_joint` conditions on surrogate likelihoods by calling `log_prob` on each
fitted surrogate. That call is the only contact point between the metamodel layer and
the surrogate layer, and it is easy for it to be exercised on one backend and silently
untested on the other — the TCR metamodel fits all four of its surrogates with
`pymc_gp`, so nothing in the repo drove `sbi_npe` through a joint sample.

The test here is the same for both backends, and it is a real one: fit a surrogate on
data generated by a known linear map, put a deliberately vague prior on the output,
and check that joint sampling pulls the output onto the surrogate's prediction. If the
likelihood were not evaluated — the pre-existing behaviour, and what `--method
propagate` still does — `y` would come back at its prior and the residual test would
fail loudly.

Both backends are optional dependencies, so each parametrisation skips when its
backend is absent. `REQUIRE_JOINT_BACKENDS=1` turns those skips into failures, per
CLAUDE.md rule 12: a gate that can skip needs a mode where skipping is an error.

**Marked `slow`, deliberately.** Cost here is dominated by surrogate evaluations, not
by sampling: a fitted NPE's `log_prob` measures ~23 ms per call against ~0.2 ms for
`pymc_gp`, so a chain that is instant on one backend takes minutes on the other. The
fast suite has a 30-second budget and CI's fast job installs both backends, so leaving
these unmarked would have put several minutes on every push, on three operating
systems. They belong in `Deep CI`, which is provisioned for exactly this.

That 100x gap is itself worth knowing when using this feature: joint sampling with NPE
surrogates is practical, but budget for it, and prefer fewer, longer chains.
"""

from __future__ import annotations

import os

import numpy as np
import pytest

from bayesian_metamodeling.meta.compiler import compile_metamodel
from bayesian_metamodeling.meta.ir import (
    MetamodelIR,
    PriorFactorIR,
    SurrogateLikelihoodFactorIR,
    VariableIR,
)
from bayesian_metamodeling.meta.joint_sampling import sample_joint
from bayesian_metamodeling.surrogates.backends import fit_backend_model
from tests.backend_support import _has_pymc, _has_sbi, is_pymc_runtime_constraint

# The map the surrogate has to learn. Deliberately simple: this test is about whether
# the metamodel layer *consults* the surrogate, not about surrogate accuracy.
ALPHA_A, ALPHA_B, INTERCEPT = 1.7, -0.8, 0.2

BACKEND_CONFIG = {
    "pymc_gp": {"draws": 200, "tune": 200, "chains": 1, "target_accept": 0.9},
    "sbi_npe": {
        "density_estimator": "maf",
        "max_num_epochs": 120,
        "training_batch_size": 32,
        "learning_rate": 5e-4,
        "summary_samples": 128,
    },
}


def _require_backends() -> bool:
    return os.getenv("REQUIRE_JOINT_BACKENDS", "").strip().lower() in {"1", "true", "yes", "on"}


def _skip_or_fail(backend: str) -> None:
    # Wording matters: Deep CI's skip audit matches "needs pymc" / "needs sbi" against
    # its SANCTIONED list. A reason it cannot match fails the job, by design.
    extra = "pymc" if backend == "pymc_gp" else "sbi"
    message = (
        f"needs {extra}: {backend} is not installed, so joint sampling is not "
        f"exercised against it here (pip install -e '.[{extra}]')."
    )
    if _require_backends():
        pytest.fail(f"REQUIRE_JOINT_BACKENDS=1: {message}")
    pytest.skip(message)


def _training_data(n: int = 240, noise: float = 0.05, seed: int = 7):
    rng = np.random.default_rng(seed)
    a = rng.uniform(-2.0, 2.0, size=n)
    b = rng.uniform(-2.0, 2.0, size=n)
    y = ALPHA_A * a + ALPHA_B * b + INTERCEPT + rng.normal(0.0, noise, size=n)
    return np.column_stack([a, b]), y.reshape(-1, 1)


def _ir_with_surrogate() -> MetamodelIR:
    """a, b tied to y only through the surrogate likelihood.

    `y`'s prior is intentionally far too wide (sd 5 around 0) so that "the posterior
    equals the prior" and "the posterior follows the surrogate" are impossible to
    confuse.
    """
    return MetamodelIR(
        name="surrogate_joint",
        variables=[VariableIR(name="a"), VariableIR(name="b"), VariableIR(name="y")],
        factors=[
            PriorFactorIR(variable="a", distribution={"kind": "normal", "loc": 0.0, "scale": 1.0}),
            PriorFactorIR(variable="b", distribution={"kind": "normal", "loc": 0.0, "scale": 1.0}),
            PriorFactorIR(variable="y", distribution={"kind": "normal", "loc": 0.0, "scale": 5.0}),
            SurrogateLikelihoodFactorIR(
                surrogate_ref="toy",
                inputs=["a", "b"],
                outputs=["y"],
            ),
        ],
    )


# NUTS explores extreme parameter values while tuning, and on some BLAS builds that
# overflows inside a dot product in pymc's own internals. `filterwarnings = error` in
# pytest.ini promotes it to a failure — which it did on Deep CI's ubuntu runners while
# passing locally three times over, including under CI's own `PYTENSOR_FLAGS=cxx=`.
#
# This is narrowed to the one message, and it is safe *because the test does not infer
# fit quality from the absence of warnings*: it asserts directly that the fitted
# surrogate prefers the true output to a wrong one before using it. A genuinely broken
# fit still fails, loudly, on an assertion that says so.
@pytest.mark.filterwarnings("ignore:overflow encountered in dot:RuntimeWarning")
@pytest.mark.slow
@pytest.mark.optional_backend
@pytest.mark.integration
@pytest.mark.parametrize("backend", ["pymc_gp", "sbi_npe"])
def test_joint_sampling_conditions_on_each_surrogate_backend(backend):
    if backend == "pymc_gp" and not _has_pymc():
        _skip_or_fail(backend)
    if backend == "sbi_npe" and not _has_sbi():
        _skip_or_fail(backend)

    x, y = _training_data()
    try:
        model = fit_backend_model(
            backend=backend,
            x=x,
            y=y,
            input_names=["a", "b"],
            output_names=["y"],
            backend_config=BACKEND_CONFIG[backend],
            seed=0,
        )
    except Exception as exc:  # noqa: BLE001 - re-raised unless it's a toolchain limit
        if backend == "pymc_gp" and is_pymc_runtime_constraint(exc):
            pytest.skip(f"pymc toolchain constraint, not a regression: {exc}")
        raise

    # Sanity: the fitted surrogate must prefer the true output to a wrong one. If this
    # fails the surrogate is broken and the joint result below would be meaningless.
    probe = {"a": np.array([1.0]), "b": np.array([0.5])}
    truth = ALPHA_A * 1.0 + ALPHA_B * 0.5 + INTERCEPT
    lp_true = float(np.asarray(model.log_prob(probe, {"y": np.array([truth])})).reshape(-1)[0])
    lp_wrong = float(
        np.asarray(model.log_prob(probe, {"y": np.array([truth + 4.0])})).reshape(-1)[0]
    )
    assert lp_true > lp_wrong, (
        f"{backend}: surrogate log_prob does not favour the true output "
        f"({lp_true:.3f} vs {lp_wrong:.3f}); the fit failed, so the joint test cannot mean anything"
    )

    samples, diag = sample_joint(
        compile_metamodel(_ir_with_surrogate()),
        draws=2000,
        tune=800,
        chains=1,
        seed=17,
        surrogates={"toy": model},
    )

    a = samples["a"].ravel()
    b = samples["b"].ravel()
    y_s = samples["y"].ravel()
    predicted = ALPHA_A * a + ALPHA_B * b + INTERCEPT
    residual_sd = float(np.std(y_s - predicted))

    # The prior on y has sd 5.0. If the surrogate likelihood were skipped, y would be
    # independent of (a, b) and the residual sd would be at least that.
    assert residual_sd < 1.0, (
        f"{backend}: y is not tracking the surrogate's prediction (residual sd "
        f"{residual_sd:.3f} against a prior sd of 5.0) — the surrogate likelihood is "
        f"not being evaluated. accept_rate={diag['accept_rate']:.2f}"
    )
    assert float(np.std(y_s)) < 5.0, (
        f"{backend}: y was not constrained at all (sd {np.std(y_s):.3f} vs prior 5.0)"
    )
    assert diag["surrogates_loaded"] == ["toy"], diag


# NUTS explores extreme parameter values while tuning, and on some BLAS builds that
# overflows inside a dot product in pymc's own internals. `filterwarnings = error` in
# pytest.ini promotes it to a failure — which it did on Deep CI's ubuntu runners while
# passing locally three times over, including under CI's own `PYTENSOR_FLAGS=cxx=`.
#
# This is narrowed to the one message, and it is safe *because the test does not infer
# fit quality from the absence of warnings*: it asserts directly that the fitted
# surrogate prefers the true output to a wrong one before using it. A genuinely broken
# fit still fails, loudly, on an assertion that says so.
@pytest.mark.filterwarnings("ignore:overflow encountered in dot:RuntimeWarning")
@pytest.mark.slow
@pytest.mark.optional_backend
@pytest.mark.parametrize("backend", ["pymc_gp", "sbi_npe"])
def test_surrogate_log_prob_accepts_the_single_row_call_the_compiler_makes(backend):
    """The compiler evaluates one point at a time; pin that calling convention.

    `CompiledMetaModel.evaluate_log_prob` builds `{name: np.array([value])}` per
    variable and reads `.reshape(-1)[0]` from the result. A backend returning a scalar,
    or requiring batched input, would break joint sampling while every batch-oriented
    surrogate test kept passing.
    """
    if backend == "pymc_gp" and not _has_pymc():
        _skip_or_fail(backend)
    if backend == "sbi_npe" and not _has_sbi():
        _skip_or_fail(backend)

    x, y = _training_data(n=120)
    try:
        model = fit_backend_model(
            backend=backend,
            x=x,
            y=y,
            input_names=["a", "b"],
            output_names=["y"],
            backend_config=BACKEND_CONFIG[backend],
            seed=0,
        )
    except Exception as exc:  # noqa: BLE001
        if backend == "pymc_gp" and is_pymc_runtime_constraint(exc):
            pytest.skip(f"pymc toolchain constraint, not a regression: {exc}")
        raise

    out = model.log_prob({"a": np.array([0.3]), "b": np.array([-0.1])}, {"y": np.array([0.4])})
    arr = np.asarray(out)
    assert arr.reshape(-1).size == 1, (
        f"{backend}: expected one value per row, got shape {arr.shape}"
    )
    assert np.isfinite(arr.reshape(-1)[0]), f"{backend}: log_prob returned {arr.reshape(-1)[0]}"
